<?php

/**
 * @file
 * Contains d7_migration_group_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d7_migration_group_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d7_migration_group_example module.
    case 'help.page.d7_migration_group_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demonstrates a Drupal 7 migration group.') . '</p>';
      return $output;

    default:
  }
}
