name: 'D7 Node Migration Example'
type: module
description: 'Demonstrates how a node can be migrated.'
core: 8.x
package: 'Migration Example modules'
dependencies:
  - migrate
  - migrate_plus
  - migrate_tools
