<?php

/**
 * @file
 * Contains d7_media_migration_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d7_media_migration_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d7_media_migration_example module.
    case 'help.page.d7_media_migration_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demonstrates how a File from Drupal 7 can be migrated to Media in Drupal 8.') . '</p>';
      return $output;

    default:
  }
}
